#!/usr/bin/env python3
"""lingxi_profiling_collector.py — Collect performance CSV data for Lingxi operator variants.

Usage:
    python3 lingxi_profiling_collector.py <task_dir> \
        --output-dir <profiling_output_dir> \
        [--device 0] \
        [--warmup 5] \
        [--repeat 10] \
        [--output result.json]

This script:
1. Tries `msprof op` (hardware-level profiling) first — captures real pipeline
   utilization data (aiv_vec_ratio, aiv_mte2_ratio, etc.) via ACL runtime
   interception of aclrtLaunchKernelWithHostArgs.
2. Falls back to host-side timing (time.perf_counter) if msprof is unavailable
   or fails.
3. Outputs JSON: {"success": bool, "profiling_dir": str, "op_summary_csv": str,
   "mode": "msprof_op"|"host_timing"}

NOTE: Lingxi operators use pybind11 direct kernel launch (not GE dispatch).
torch_npu.profiler cannot capture TASK-level data for this launch path, but
`msprof op` works because it intercepts at the ACL runtime layer.
"""

import argparse
import csv
import glob
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import textwrap
import time
import traceback
from pathlib import Path


def _load_module_from_path(module_name: str, file_path: str):
    """Dynamically load a Python module from a file path."""
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    if spec is None:
        raise ImportError(f"Cannot create module spec from {file_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def _find_op_summary_csv(profiling_dir: str) -> str:
    """Find the most recent op_summary CSV under profiling_dir.

    Search order:
    1. op_summary_*.csv (msprof native or generated by this script)
    2. kernel_details.csv (torch_npu.profiler alternative)
    """
    # Pattern 1: standard mindstudio_profiler_output
    pattern1 = str(Path(profiling_dir) / "*" / "PROF_*"
                    / "mindstudio_profiler_output" / "op_summary_*.csv")
    csv_files = glob.glob(pattern1)

    # Pattern 2: ASCEND_PROFILER_OUTPUT
    if not csv_files:
        pattern2 = str(Path(profiling_dir) / "*" / "ASCEND_PROFILER_OUTPUT" / "op_summary_*.csv")
        csv_files = glob.glob(pattern2)

    # Pattern 3: recursive fallback
    if not csv_files:
        all_files = glob.glob(str(Path(profiling_dir) / "**" / "op_summary_*.csv"), recursive=True)
        csv_files = [f for f in all_files if "origin_data" not in f] or all_files

    # Fallback: kernel_details.csv
    if not csv_files:
        pattern_kd = str(Path(profiling_dir) / "**" / "kernel_details.csv")
        csv_files = glob.glob(pattern_kd, recursive=True)

    if not csv_files:
        return None
    return max(csv_files, key=os.path.getmtime)


def _find_msprof():
    """Find the msprof executable.

    Search order:
    1. $ASCEND_HOME_PATH/bin/msprof
    2. which msprof (PATH lookup)
    """
    ascend_home = os.environ.get("ASCEND_HOME_PATH", "")
    if ascend_home:
        candidate = os.path.join(ascend_home, "bin", "msprof")
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return shutil.which("msprof")


def _generate_runner_script(task_dir, output_path, device, warmup, repeat):
    """Generate a standalone Python script that msprof op can wrap.

    The script loads model_new_ascendc.py, gets inputs, moves to NPU,
    and runs warmup + repeat forward passes.  It is designed to be
    executed as: msprof op --application="python3 <runner.py>" ...
    """
    script = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"Auto-generated runner for msprof op profiling.\"\"\"
        import sys, os, importlib.util

        TASK_DIR = {task_dir!r}
        DEVICE = {device!r}
        WARMUP = {warmup!r}
        REPEAT = {repeat!r}

        def _load_module(name, path):
            spec = importlib.util.spec_from_file_location(name, path)
            mod = importlib.util.module_from_spec(spec)
            sys.modules[name] = mod
            spec.loader.exec_module(mod)
            return mod

        def main():
            import torch
            import torch_npu  # noqa: F401

            torch.npu.set_device(DEVICE)

            if TASK_DIR not in sys.path:
                sys.path.insert(0, TASK_DIR)

            model_path = os.path.join(TASK_DIR, "model_new_ascendc.py")
            mod = _load_module("model_new_ascendc", model_path)

            # Get inputs
            input_groups = None
            if hasattr(mod, "get_input_groups"):
                input_groups = mod.get_input_groups()
            elif hasattr(mod, "get_inputs"):
                input_groups = [mod.get_inputs()]
            if not input_groups:
                ref_path = os.path.join(TASK_DIR, "model.py")
                if os.path.isfile(ref_path):
                    ref = _load_module("model_ref", ref_path)
                    if hasattr(ref, "get_input_groups"):
                        input_groups = ref.get_input_groups()
                    elif hasattr(ref, "get_inputs"):
                        input_groups = [ref.get_inputs()]
            if not input_groups:
                print("ERROR: no input provider found", file=sys.stderr)
                sys.exit(1)

            inputs = input_groups[0]
            npu_inputs = [x.npu() if isinstance(x, torch.Tensor) else x for x in inputs]

            # Get model callable
            model_fn = None
            for cls_name in ("ModelNewAscendC", "ModelNew", "Model"):
                if hasattr(mod, cls_name):
                    model_fn = getattr(mod, cls_name)().forward
                    break
            if model_fn is None:
                model_fn = getattr(mod, "forward", None) or getattr(mod, "run", None)
            if model_fn is None:
                print("ERROR: no model callable found", file=sys.stderr)
                sys.exit(1)

            # Warmup
            for _ in range(WARMUP):
                model_fn(*npu_inputs)
            torch.npu.synchronize()

            # Timed iterations (msprof captures the hardware events)
            for _ in range(REPEAT):
                model_fn(*npu_inputs)
            torch.npu.synchronize()

        if __name__ == "__main__":
            main()
    """)
    with open(output_path, "w") as f:
        f.write(script)
    return output_path


def _merge_msprof_op_csvs(opprof_dir, output_dir):
    """Merge msprof op output (OpBasicInfo.csv + PipeUtilization.csv) into
    an op_summary-compatible CSV that analyze_profiling.py can consume.

    msprof op outputs to OPPROF_*/  with two key files:
    - OpBasicInfo.csv: Op Name, Task Duration(us), Block Dim, etc.
    - PipeUtilization.csv: per-block pipeline ratios (aic_*/aiv_* columns)

    PipeUtilization.csv has per-sub-block rows (cube0, vector0, vector1, ...);
    we aggregate across vector sub-blocks (max ratio) and cube sub-blocks to
    produce a single-row op_summary for the downstream analyzer.

    Returns:
        Path to generated op_summary CSV, or None on failure.
    """
    # Find the OPPROF_* directory
    opprof_dirs = glob.glob(str(Path(opprof_dir) / "OPPROF_*"))
    if not opprof_dirs:
        return None
    opprof = max(opprof_dirs, key=os.path.getmtime)

    basic_path = os.path.join(opprof, "OpBasicInfo.csv")
    pipe_path = os.path.join(opprof, "PipeUtilization.csv")
    if not os.path.isfile(basic_path) or not os.path.isfile(pipe_path):
        return None

    # Read OpBasicInfo
    with open(basic_path, "r") as f:
        reader = csv.DictReader(f)
        basic_rows = list(reader)
    if not basic_rows:
        return None
    basic = basic_rows[0]

    op_name = basic.get("Op Name", "CustomOp")
    task_dur = basic.get("Task Duration(us)", "0")
    block_dim = basic.get("Block Dim", "1")
    mix_block_dim = basic.get("Mix Block Dim", "0")
    device_id = basic.get("Device Id", "0")

    # Read PipeUtilization — aggregate across sub-blocks
    with open(pipe_path, "r") as f:
        reader = csv.DictReader(f)
        pipe_rows = list(reader)

    def _safe(row, key):
        v = row.get(key, "NA")
        if v in ("NA", "", None):
            return 0.0
        try:
            return float(v)
        except (ValueError, TypeError):
            return 0.0

    # Separate aic (cube) and aiv (vector) rows by sub_block_id prefix
    aic_rows = [r for r in pipe_rows if r.get("sub_block_id", "").startswith("cube")]
    aiv_rows = [r for r in pipe_rows if r.get("sub_block_id", "").startswith("vector")]

    # For each pipeline metric, take the max across sub-blocks
    # (the bottleneck sub-block determines the overall ratio)
    aic_keys = [
        ("aic_time(us)", "aicore_time(us)"),
        ("aic_total_cycles", "aic_total_cycles"),
        ("aic_cube_time(us)", "aic_mac_time(us)"),
        ("aic_cube_ratio", "aic_mac_ratio"),
        ("aic_scalar_time(us)", "aic_scalar_time(us)"),
        ("aic_scalar_ratio", "aic_scalar_ratio"),
        ("aic_mte1_time(us)", "aic_mte1_time(us)"),
        ("aic_mte1_ratio", "aic_mte1_ratio"),
        ("aic_mte2_time(us)", "aic_mte2_time(us)"),
        ("aic_mte2_ratio", "aic_mte2_ratio"),
        ("aic_fixpipe_time(us)", "aic_fixpipe_time(us)"),
        ("aic_fixpipe_ratio", "aic_fixpipe_ratio"),
        ("aic_icache_miss_rate", "aic_icache_miss_rate"),
    ]
    aiv_keys = [
        ("aiv_time(us)", "aiv_time(us)"),
        ("aiv_total_cycles", "aiv_total_cycles"),
        ("aiv_vec_time(us)", "aiv_vec_time(us)"),
        ("aiv_vec_ratio", "aiv_vec_ratio"),
        ("aiv_scalar_time(us)", "aiv_scalar_time(us)"),
        ("aiv_scalar_ratio", "aiv_scalar_ratio"),
        ("aiv_mte2_time(us)", "aiv_mte2_time(us)"),
        ("aiv_mte2_ratio", "aiv_mte2_ratio"),
        ("aiv_mte3_time(us)", "aiv_mte3_time(us)"),
        ("aiv_mte3_ratio", "aiv_mte3_ratio"),
        ("aiv_icache_miss_rate", "aiv_icache_miss_rate"),
    ]

    merged = {}
    for src_key, dst_key in aic_keys:
        vals = [_safe(r, src_key) for r in aic_rows]
        merged[dst_key] = max(vals) if vals else 0.0
    for src_key, dst_key in aiv_keys:
        vals = [_safe(r, src_key) for r in aiv_rows]
        merged[dst_key] = max(vals) if vals else 0.0

    # Determine task type from sub_block presence
    has_aic = bool(aic_rows)
    has_aiv = bool(aiv_rows)
    if has_aic and has_aiv:
        task_type = "MIX_AIC"
    elif has_aic:
        task_type = "AI_CORE"
    else:
        task_type = "AI_VECTOR_CORE"

    # Build op_summary CSV
    header = [
        "Device_id", "Model ID", "Task ID", "Stream ID",
        "Op Name", "OP Type", "OP State", "Task Type",
        "Task Start Time(us)", "Task Duration(us)", "Task Wait Time(us)",
        "Block Dim", "Mix Block Dim", "HF32 Eligible",
        "Input Shapes", "Input Data Types", "Input Formats",
        "Output Shapes", "Output Data Types", "Output Formats",
        "Context ID",
        "aicore_time(us)", "aic_total_cycles",
        "aic_mac_time(us)", "aic_mac_ratio",
        "aic_scalar_time(us)", "aic_scalar_ratio",
        "aic_mte1_time(us)", "aic_mte1_ratio",
        "aic_mte2_time(us)", "aic_mte2_ratio",
        "aic_fixpipe_time(us)", "aic_fixpipe_ratio",
        "aic_icache_miss_rate",
        "aiv_time(us)", "aiv_total_cycles",
        "aiv_vec_time(us)", "aiv_vec_ratio",
        "aiv_scalar_time(us)", "aiv_scalar_ratio",
        "aiv_mte2_time(us)", "aiv_mte2_ratio",
        "aiv_mte3_time(us)", "aiv_mte3_ratio",
        "aiv_icache_miss_rate",
        "cube_utilization(%)",
    ]

    row = [
        device_id, 4294967295, 0, 0,
        op_name, op_name, "dynamic", task_type,
        0.0, task_dur, 0.0,
        block_dim, mix_block_dim, "NO",
        "N/A", "N/A", "N/A",
        "N/A", "N/A", "N/A",
        "",
        merged.get("aicore_time(us)", 0.0),
        merged.get("aic_total_cycles", 0.0),
        merged.get("aic_mac_time(us)", 0.0),
        merged.get("aic_mac_ratio", 0.0),
        merged.get("aic_scalar_time(us)", 0.0),
        merged.get("aic_scalar_ratio", 0.0),
        merged.get("aic_mte1_time(us)", 0.0),
        merged.get("aic_mte1_ratio", 0.0),
        merged.get("aic_mte2_time(us)", 0.0),
        merged.get("aic_mte2_ratio", 0.0),
        merged.get("aic_fixpipe_time(us)", 0.0),
        merged.get("aic_fixpipe_ratio", 0.0),
        merged.get("aic_icache_miss_rate", 0.0),
        merged.get("aiv_time(us)", 0.0),
        merged.get("aiv_total_cycles", 0.0),
        merged.get("aiv_vec_time(us)", 0.0),
        merged.get("aiv_vec_ratio", 0.0),
        merged.get("aiv_scalar_time(us)", 0.0),
        merged.get("aiv_scalar_ratio", 0.0),
        merged.get("aiv_mte2_time(us)", 0.0),
        merged.get("aiv_mte2_ratio", 0.0),
        merged.get("aiv_mte3_time(us)", 0.0),
        merged.get("aiv_mte3_ratio", 0.0),
        merged.get("aiv_icache_miss_rate", 0.0),
        0.0,  # cube_utilization
    ]

    csv_name = f"op_summary_{int(time.time())}.csv"
    csv_path = os.path.join(output_dir, csv_name)
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerow(row)

    print(f"[cv_csv_profiling] Merged msprof op CSVs → {csv_path}")
    return csv_path


def _run_msprof_op(task_dir, output_dir, device, warmup, repeat):
    """Run msprof op to collect hardware-level profiling data.

    msprof op intercepts aclrtLaunchKernelWithHostArgs at the ACL runtime
    layer, so it can capture pipeline utilization data even for pybind11
    direct-launch kernels that bypass GE dispatch.

    Returns:
        dict with keys: success, op_summary_csv, error, mode
    """
    result = {
        "success": False,
        "op_summary_csv": "",
        "error": "",
        "mode": "msprof_op",
    }

    # Check msprof availability
    msprof_path = _find_msprof()
    if not msprof_path:
        result["error"] = "msprof executable not found"
        return result

    # Generate runner script
    runner_path = os.path.join(output_dir, "_msprof_runner.py")
    try:
        _generate_runner_script(task_dir, runner_path, device, warmup, repeat)
    except Exception as e:
        result["error"] = f"Failed to generate runner script: {e}"
        return result

    # Prepare msprof output directory
    msprof_output = os.path.join(output_dir, "msprof_output")
    os.makedirs(msprof_output, exist_ok=True)

    # Build msprof op command
    python_exe = sys.executable or "python3"
    cmd = [
        msprof_path, "op",
        f"--application={python_exe} {runner_path}",
        f"--output={msprof_output}",
        "--aic-metrics=PipeUtilization",
    ]

    print(f"[cv_csv_profiling] Running msprof op: {' '.join(cmd)}")

    # Execute msprof op with timeout
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=180,
            cwd=task_dir,
        )
        if proc.returncode != 0:
            stderr_tail = (proc.stderr or "")[-500:]
            result["error"] = (
                f"msprof op exited with code {proc.returncode}: {stderr_tail}"
            )
            print(f"[cv_csv_profiling] msprof op stderr: {stderr_tail}")
            return result
    except subprocess.TimeoutExpired:
        result["error"] = "msprof op timed out after 180s"
        return result
    except Exception as e:
        result["error"] = f"msprof op execution failed: {e}"
        return result

    # Find and merge the output CSVs (OpBasicInfo + PipeUtilization → op_summary)
    csv_path = _merge_msprof_op_csvs(msprof_output, output_dir)
    if not csv_path:
        # Fallback: maybe msprof produced op_summary directly (future versions)
        csv_path = _find_op_summary_csv(msprof_output)
    if not csv_path:
        result["error"] = (
            f"msprof op completed but no op_summary CSV found under {msprof_output}"
        )
        return result

    result["success"] = True
    result["op_summary_csv"] = csv_path
    print(f"[cv_csv_profiling] msprof op succeeded, CSV: {csv_path}")
    return result


def _generate_op_summary_csv(
    output_dir: str,
    op_name: str,
    task_type: str,
    timings_us: list,
    device: int,
) -> str:
    """Generate an op_summary-compatible CSV from host-side timing measurements.

    The CSV has the same column schema as msprof op_summary so that
    analyze_profiling.py can consume it.  Pipeline ratio columns are left
    at 0 because pybind11 direct-launch kernels do not expose PMU data.
    """
    csv_name = f"op_summary_{int(time.time())}.csv"
    csv_path = os.path.join(output_dir, csv_name)

    header = [
        "Device_id", "Model ID", "Task ID", "Stream ID",
        "Op Name", "OP Type", "OP State", "Task Type",
        "Task Start Time(us)", "Task Duration(us)", "Task Wait Time(us)",
        "Block Dim", "Mix Block Dim", "HF32 Eligible",
        "Input Shapes", "Input Data Types", "Input Formats",
        "Output Shapes", "Output Data Types", "Output Formats",
        "Context ID",
        "aicore_time(us)", "aic_total_cycles",
        "aic_mac_time(us)", "aic_mac_ratio",
        "aic_scalar_time(us)", "aic_scalar_ratio",
        "aic_mte1_time(us)", "aic_mte1_ratio",
        "aic_mte2_time(us)", "aic_mte2_ratio",
        "aic_fixpipe_time(us)", "aic_fixpipe_ratio",
        "aic_icache_miss_rate",
        "aiv_time(us)", "aiv_total_cycles",
        "aiv_vec_time(us)", "aiv_vec_ratio",
        "aiv_scalar_time(us)", "aiv_scalar_ratio",
        "aiv_mte2_time(us)", "aiv_mte2_ratio",
        "aiv_mte3_time(us)", "aiv_mte3_ratio",
        "aiv_icache_miss_rate",
        "cube_utilization(%)",
    ]

    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for idx, dur_us in enumerate(timings_us):
            row = [
                device, 4294967295, idx, 0,
                op_name, op_name, "dynamic", task_type,
                0.0, round(dur_us, 3), 0.0,
                1, 0, "NO",
                "N/A", "N/A", "N/A",
                "N/A", "N/A", "N/A",
                "",
            ] + [0.0] * 24  # pipeline ratio columns (unavailable for pybind11 launch)
            writer.writerow(row)

    return csv_path


def collect_profiling(
    task_dir: str,
    output_dir: str,
    device: int = 0,
    warmup: int = 5,
    repeat: int = 10,
) -> dict:
    """Collect performance data for a Lingxi operator.

    Strategy:
    1. Try `msprof op` first — captures real hardware pipeline utilization
       (aiv_vec_ratio, aiv_mte2_ratio, etc.) by intercepting at ACL runtime.
    2. Fall back to host-side timing if msprof is unavailable or fails.

    Args:
        task_dir: Path to the task directory (containing model_new_ascendc.py)
        output_dir: Directory where profiling output will be written
        device: NPU device ID
        warmup: Number of warmup iterations
        repeat: Number of timed iterations

    Returns:
        {"success": bool, "profiling_dir": str, "op_summary_csv": str,
         "error": str, "mode": "msprof_op"|"host_timing"}
    """
    result = {
        "success": False,
        "profiling_dir": output_dir,
        "op_summary_csv": "",
        "error": "",
        "mode": "",
    }

    # --- Step 0: Validate task directory ---
    task_dir = str(Path(task_dir).resolve())
    model_path = os.path.join(task_dir, "model_new_ascendc.py")
    if not os.path.isfile(model_path):
        result["error"] = f"model_new_ascendc.py not found at {model_path}"
        return result

    os.makedirs(output_dir, exist_ok=True)

    # --- Step 1: Try msprof op (hardware-level profiling) ---
    print("[cv_csv_profiling] Attempting msprof op for hardware profiling...")
    msprof_result = _run_msprof_op(task_dir, output_dir, device, warmup, repeat)

    if msprof_result["success"]:
        result["success"] = True
        result["op_summary_csv"] = msprof_result["op_summary_csv"]
        result["mode"] = "msprof_op"
        print("[cv_csv_profiling] msprof op succeeded — real pipeline data available")
        return result

    # msprof op failed — log warning and fall back to host-side timing
    print(f"[cv_csv_profiling] WARNING: msprof op failed: {msprof_result['error']}")
    print("[cv_csv_profiling] Falling back to host-side timing...")

    # --- Step 2: Host-side timing fallback ---
    # Import dependencies
    try:
        import torch
        import torch_npu  # noqa: F401
    except ImportError as e:
        result["error"] = f"Import error: {e}. Ensure torch and torch_npu are installed."
        return result

    # Set device
    try:
        torch.npu.set_device(device)
    except Exception as e:
        result["error"] = f"Failed to set NPU device {device}: {e}"
        return result

    # Load model_new_ascendc.py
    try:
        if task_dir not in sys.path:
            sys.path.insert(0, task_dir)
        model_module = _load_module_from_path("model_new_ascendc", model_path)
    except Exception as e:
        result["error"] = f"Failed to load model_new_ascendc.py: {e}"
        return result

    # Get input groups
    try:
        input_groups = None
        if hasattr(model_module, "get_input_groups"):
            input_groups = model_module.get_input_groups()
        elif hasattr(model_module, "get_inputs"):
            input_groups = [model_module.get_inputs()]

        if not input_groups:
            model_py_path = os.path.join(task_dir, "model.py")
            if os.path.isfile(model_py_path):
                ref_module = _load_module_from_path("model_ref", model_py_path)
                if hasattr(ref_module, "get_input_groups"):
                    input_groups = ref_module.get_input_groups()
                elif hasattr(ref_module, "get_inputs"):
                    input_groups = [ref_module.get_inputs()]

        if not input_groups:
            result["error"] = (
                "Neither model_new_ascendc.py nor model.py provides "
                "get_input_groups() or get_inputs()"
            )
            return result
    except Exception as e:
        result["error"] = f"Failed to get inputs: {e}"
        return result

    if not input_groups:
        result["error"] = "get_input_groups() returned empty list"
        return result

    inputs = input_groups[0]

    # Get model callable
    try:
        model_fn = None
        op_name = "CustomOp"
        for cls_name in ("ModelNewAscendC", "ModelNew", "Model"):
            if hasattr(model_module, cls_name):
                model_cls = getattr(model_module, cls_name)
                model_instance = model_cls()
                model_fn = model_instance.forward
                op_name = cls_name
                break

        if model_fn is None:
            if hasattr(model_module, "forward"):
                model_fn = model_module.forward
            elif hasattr(model_module, "run"):
                model_fn = model_module.run

        if model_fn is None:
            result["error"] = (
                "model_new_ascendc.py has no recognizable model class "
                "(ModelNewAscendC/ModelNew/Model) or forward()/run() function"
            )
            return result
    except Exception as e:
        result["error"] = f"Failed to instantiate model: {e}"
        return result

    # Move inputs to NPU
    try:
        import torch
        npu_inputs = []
        for inp in inputs:
            if isinstance(inp, torch.Tensor):
                npu_inputs.append(inp.npu())
            else:
                npu_inputs.append(inp)
    except Exception as e:
        result["error"] = f"Failed to move inputs to NPU: {e}"
        return result

    # Warmup
    try:
        for _ in range(warmup):
            model_fn(*npu_inputs)
        torch.npu.synchronize()
    except Exception as e:
        result["error"] = f"Warmup failed: {e}"
        return result

    # Timed iterations (host-side)
    try:
        timings_us = []
        for _ in range(repeat):
            torch.npu.synchronize()
            t0 = time.perf_counter()
            model_fn(*npu_inputs)
            torch.npu.synchronize()
            t1 = time.perf_counter()
            timings_us.append((t1 - t0) * 1e6)  # seconds → microseconds
    except Exception as e:
        result["error"] = f"Timing loop failed: {e}\n{traceback.format_exc()}"
        return result

    # Generate CSV and assemble result
    try:
        task_type = "AI_VECTOR_CORE"  # default for most CV pybind11 kernels
        csv_path = _generate_op_summary_csv(
            output_dir, op_name, task_type, timings_us, device,
        )
        result["success"] = True
        result["op_summary_csv"] = csv_path
        result["mode"] = "host_timing"

        avg_us = sum(timings_us) / len(timings_us)
        min_us = min(timings_us)
        max_us = max(timings_us)
        print(f"[cv_csv_profiling] {op_name}: "
              f"avg={avg_us:.1f}us  min={min_us:.1f}us  max={max_us:.1f}us  "
              f"({repeat} iters, {warmup} warmup)")
        print(f"[cv_csv_profiling] CSV written to: {csv_path}")
        print("[cv_csv_profiling] NOTE: host-side timing — pipeline ratios are 0")
    except Exception as e:
        result["error"] = f"CSV generation failed: {e}\n{traceback.format_exc()}"
        return result

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Collect Lingxi operator performance via host-side timing"
    )
    parser.add_argument("task_dir", help="Path to task directory with model_new_ascendc.py")
    parser.add_argument("--output-dir", required=True, help="Profiling output directory")
    parser.add_argument("--device", type=int, default=0, help="NPU device ID")
    parser.add_argument("--warmup", type=int, default=5, help="Warmup iterations")
    parser.add_argument("--repeat", type=int, default=10, help="Timed iterations")
    parser.add_argument("--output", default="profiling_collection.json",
                        help="Output JSON file path")
    args = parser.parse_args()

    result = collect_profiling(
        task_dir=args.task_dir,
        output_dir=args.output_dir,
        device=args.device,
        warmup=args.warmup,
        repeat=args.repeat,
    )

    output_path = args.output
    if not os.path.isabs(output_path):
        output_path = os.path.join(args.output_dir, output_path)
    with open(output_path, "w") as f:
        json.dump(result, f, indent=2)
    print(f"[cv_csv_profiling] Result JSON: {output_path}")

    sys.exit(0 if result["success"] else 1)


if __name__ == "__main__":
    main()
